"""Study plan writer tool — owned by Member D (Study Planner Agent).

Renders the final 7-day study plan to a Markdown file inside `outputs/`.
The path is returned so it can be stored in StudyState for the demo.
"""
from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import List, TypedDict

from core.logger import get_logger

_logger = get_logger("tool.study_plan_writer")

_OUTPUT_DIR = Path(__file__).resolve().parent.parent / "outputs"
_SLUG_RE = re.compile(r"[^a-zA-Z0-9]+")


class Flashcard(TypedDict):
    question: str
    answer: str


class StudyPlanWriteError(RuntimeError):
    """Raised when the output file cannot be created or written."""


def _slugify(text: str) -> str:
    """Lowercase + collapse non-alphanumerics to underscores. Always non-empty."""
    slug = _SLUG_RE.sub("_", text.strip().lower()).strip("_")
    return slug or "topic"


def write_study_plan(
    topic: str,
    knowledge_brief: str,
    practice_questions: List[Flashcard],
    plan_body: str,
    output_dir: Path = _OUTPUT_DIR,
) -> str:
    """Write the assembled study plan to a Markdown file.

    Args:
        topic: Topic the plan is built around. Used in the title and filename.
        knowledge_brief: The 3-bullet brief from the GapAnalystAgent.
        practice_questions: Q/A pairs from the QuestionGeneratorAgent.
        plan_body: The 7-day plan text generated by the StudyPlannerAgent.
        output_dir: Override the default `outputs/` directory.

    Returns:
        Absolute path to the written Markdown file as a string.

    Raises:
        ValueError: If `topic` or `plan_body` is empty/whitespace.
        StudyPlanWriteError: If the file cannot be created or written.
    """
    if not topic or not topic.strip():
        raise ValueError("topic must be a non-empty string.")
    if not plan_body or not plan_body.strip():
        raise ValueError("plan_body must be a non-empty string.")

    output_dir = Path(output_dir)
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise StudyPlanWriteError(f"Could not create {output_dir}: {exc}") from exc

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = output_dir / f"study_plan_{_slugify(topic)}_{timestamp}.md"

    parts: List[str] = [
        f"# Personalized Study Plan: {topic.strip()}",
        f"_Generated: {datetime.now().isoformat(timespec='seconds')}_",
        "",
        "## 1. Knowledge Brief",
        (knowledge_brief.strip() or "_(no brief produced)_"),
        "",
        "## 2. Practice Questions",
    ]
    if practice_questions:
        for idx, card in enumerate(practice_questions, start=1):
            q = (card.get("question") or "").strip()
            a = (card.get("answer") or "").strip()
            parts.append(f"**Q{idx}.** {q}")
            parts.append(f"> {a}")
            parts.append("")
    else:
        parts.append("_(no questions generated)_")
        parts.append("")

    parts.append("## 3. 7-Day Study Plan")
    parts.append(plan_body.strip())
    parts.append("")

    try:
        file_path.write_text("\n".join(parts), encoding="utf-8")
    except OSError as exc:
        raise StudyPlanWriteError(f"Could not write {file_path}: {exc}") from exc

    _logger.info("Wrote study plan to %s", file_path)
    return str(file_path)
